### PR TITLE
Add support for subscriptions of concrete instances rather than relying on DI

### PR DESCRIPTION
**Pull request by CoryCharlton**
This implements the changes required for CShark-Hub/Mako-IoT.Home/issues/66

### CODE REVIEW

**Comment by CoryCharlton** [comment]
@jazzman55 It says no reviews requested but I can't find the button to request a review so consider this my request :)

**Comment by jazzman55** [comment]
@CoryCharlton that looks good! Thanks for cleaning up the tests as well :) Would you mind updating readme with usage example of the added methods, please?

**Comment by CoryCharlton** [comment]
> @CoryCharlton that looks good! Thanks for cleaning up the tests as well :) Would you mind updating readme with usage example of the added methods, please?

Done 👍

**Review by jazzman55 — APPROVED** [review]
Looks good

**Pull request merged**
